#! /bin/sh

set -e

if [ "$1" = purge ]; then
        userdel -r asterisk 2>/dev/null || true
        rm -fR /var/log/asterisk

fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d asterisk remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

